-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
local map = vim.keymap.set
local dap = require("dap")
local overseer = require("overseer")
map("i", "jj", "<esc>")
map("n", "<F5>", function()
	dap.continue()
end)
map("n", "<F6>", function()
	dap.disconnect({ terminateDebuggee = true })
end)
map("n", "<F10>", function()
	dap.step_over()
end)
map("n", "<F11>", function()
	dap.step_into()
end)
map("n", "<F12>", function()
	dap.step_out()
end)
map("n", "<Leader>b", function()
	dap.toggle_breakpoint()
end)
map("n", "<Leader>o", function()
	overseer.toggle()
end)
map("n", "<Leader>R", function()
	overseer.run_template()
end)
